name: Deploy App to Yandex Cloud S3

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@v2
        with:
          path: |
            .cache
            public
          key: ${{ runner.os }}-gatsby-ingria-songbook-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-ingria-songbook-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          region: 'ru-central1'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy to S3
        run: s3cmd --host=storage.yandexcloud.net --host-bucket =%(bucket)s.storage.yandexcloud.net sync public s3://www.ingria-songbook.ru/